UseCase를 구현하고, DI를 도입합니다.
kimdoori/GitHubApp pull request #16
Opened 2021-01-21 14:14 UTC by kimdoori

# tl;dr

#15 UseCase를 구현합니다. DI를 도입합니다.

# 주요 변경 내용

-  잘못된 디렉토리 구조를 변경했습니다.
- UseCase를 구현했습니다.
- DI를 위해 Hilt를 도입했습니다.
- retrofit 관련 빠져있던 의존성을 추가 및 수정했습니다.
- NetworkModule, ServiceModule, DataSourceModule, RepositoryModule, UseCaseModule 을 구현했습니다.
- 빈 MainActivity를 추가했습니다.

# 코드 리뷰

4주차 목표였던 UseCase 구현, DI 도입을 2개의 이슈를 나누려다가 리뷰 핑퐁이 힘들 것 같아 한 이슈에서 진행했습니다.
최대한 커밋은 잘게 쪼개보았습니다!

## 참고 사항

아키텍쳐가 슬슬 눈에 익기 시작했습니다 ✨  곧 테스트 코드도 작성해 봐야겠어요!
일단 컴파일 에러 및 빌드 에러가 발생하지 않는 것을 확인하고 올리긴 했지만 기능 테스트를 해본 건 아니라서 아직 확신이 없네요.. 얼른 presentation 레이어도 구현해서 실제 돌아가는 걸 확인해보고 싶어요 💪

2021-01-22 10:11 UTC, BeokBeok requested changes
> 아키텍쳐가 슬슬 눈에 익기 시작했습니다 ✨

굉장히 뿌듯하네요 😄 

dagger-hilt 적용해보시니 어떠신가요? koin 과 비슷한 러닝커브인가요?
약간의 코맨트가 있습니다 😄

2021-01-22 10:11 UTC, BeokBeok commented on common.gradle
> +    kapt HiltDependency.COMPILER
```suggestion
    implementation HiltDependency.HILT
    kapt HiltDependency.COMPILER
    
    implementation RetrofitDependency.CONVERTER_MOSHI
    implementation RetrofitDependency.ADAPTER_RXJAVA3
```

관련있는 것끼리 묶는 것은 어떠신가요?

2021-01-22 10:11 UTC, BeokBeok commented on buildSrc/src/main/java/Dependency.kt
> +    private const val VERSION = "2.28-alpha"
최신 버전은 `2.31.1-alpha` 까지 나왔는데, 최신 버전을 쓰지 않으시는 이유가 있나요?

2021-01-22 10:11 UTC, BeokBeok commented on data/src/main/java/com/kimdoori/githubapp/data/di/NetworkModule.kt
> +        RxJava3CallAdapterFactory.createWithScheduler(Schedulers.io())
```suggestion
        RxJava3CallAdapterFactory.createWithScheduler(Schedulers.io())
```
👍

2021-01-22 10:11 UTC, BeokBeok commented on domain/src/main/java/com/kimdoori/githubapp/domain/usecase/GitHubRepoUseCase.kt
> +class GitHubRepoUseCase(private val gitHubRepoRepository: GitHubRepoRepository) {
UseCase 도 인터페이스가 있으면 좋을 것 같습니다

2021-01-22 10:11 UTC, BeokBeok commented on domain/src/main/java/com/kimdoori/githubapp/domain/usecase/GitHubRepoUseCase.kt
> +class GitHubRepoUseCase(private val gitHubRepoRepository: GitHubRepoRepository) {
```suggestion
class GitHubRepoUseCase @Inject constructor(private val gitHubRepoRepository: GitHubRepoRepository) {
```

`@Inject` 어노테이션이 있어야만 dagger 에서 injection 이 됩니다 😄 
DataSource, Repository 에도 적용시켜주세요 🙏

2021-01-26 10:49 UTC, kimdoori commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="uiMode"
앗......... 확인용으로 간단하게 activity만 추가하려고 했는데 복붙의 폐해입니다...

2021-01-26 10:49 UTC, kimdoori commented on app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
이것도 마찬가지로 복붙의 흔적입니다 😢  레퍼 감사합니다!!

2021-01-26 10:51 UTC, kimdoori commented on domain/src/main/java/com/kimdoori/githubapp/domain/usecase/GitHubRepoUseCase.kt
> +class GitHubRepoUseCase(private val gitHubRepoRepository: GitHubRepoRepository) {
앗!!! 감사합니다!

2021-01-26 10:51 UTC, kimdoori commented on domain/src/main/java/com/kimdoori/githubapp/domain/usecase/GitHubRepoUseCase.kt
> +class GitHubRepoUseCase(private val gitHubRepoRepository: GitHubRepoRepository) {
앗... 체크 감사합니다!!

2021-01-26 10:54 UTC, kimdoori commented on buildSrc/src/main/java/Dependency.kt
> +    private const val VERSION = "2.28-alpha"
앗 안드로이드 공식 문서를 보고 따라했는데 거기에는 `2.28-alpha`라고 적혀있어서 이게 최신 버전으로 알았습니다 ㅠㅠ!! 알려주셔서 감사해요!

2021-01-26 11:08 UTC, kimdoori commented on app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
https://github.com/kimdoori/GitHubApp/pull/16/commits/50f2dac2bd42b5bd20cde86ed4cca242bf7e38ed 반영했습니다!

2021-01-26 11:09 UTC, kimdoori commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="uiMode"
https://github.com/kimdoori/GitHubApp/pull/16/commits/9a496f591b966afd6ac563ac81125fdb1987c1a6 반영했습니다!

2021-01-26 11:09 UTC, kimdoori commented on common.gradle
> +    kapt HiltDependency.COMPILER
https://github.com/kimdoori/GitHubApp/pull/16/commits/10feb5b9eeef4e37826e934330472fed6ef775e5 좋습니다! 반영했습니다!

2021-01-26 11:10 UTC, kimdoori commented on buildSrc/src/main/java/Dependency.kt
> +    private const val VERSION = "2.28-alpha"
https://github.com/kimdoori/GitHubApp/pull/16/commits/ba4cf11166a7af1ed9ac205fea32af44beb6c7c8 올렸습니다!

2021-01-26 11:11 UTC, kimdoori commented on domain/src/main/java/com/kimdoori/githubapp/domain/usecase/GitHubRepoUseCase.kt
> +class GitHubRepoUseCase(private val gitHubRepoRepository: GitHubRepoRepository) {
https://github.com/kimdoori/GitHubApp/pull/16/commits/fd0355127fcd8e7720c05f88f45e30e15bc2ee3b 반영했습니다!

2021-01-26 11:33 UTC, kimdoori commented on domain/src/main/java/com/kimdoori/githubapp/domain/usecase/GitHubRepoUseCase.kt
> +class GitHubRepoUseCase(private val gitHubRepoRepository: GitHubRepoRepository) {
https://github.com/kimdoori/GitHubApp/pull/16/commits/440946ebabe54bb9ffc860dce09ef50fcf919899 적용했습니다!

2021-01-26 11:34 UTC, kimdoori commented on buildSrc/src/main/java/Dependency.kt
> +    private const val VERSION = "2.28-alpha"
ApplicationComponent가 deprecated 돼서 SingletonComponent 사용하도록 변경했습니다! https://github.com/kimdoori/GitHubApp/pull/16/commits/6b8d17e71e285aff03db8fe6462fb4d06261c769

2021-01-26 11:35 UTC, kimdoori commented
implementation을 사용하면 제대로 못 불러와서 에러가 나길래 api를 사용하도록 변경했습니다! https://github.com/kimdoori/GitHubApp/pull/16/commits/8f1f78e9880ce4b3e37905a42aa7cfbec6e58ea9

2021-01-26 11:38 UTC, kimdoori commented
@BeokBeok 리뷰 봐주셔서 감사해요! 반영했습니다 😊 

> dagger-hilt 적용해보시니 어떠신가요? koin 과 비슷한 러닝커브인가요?

넵 ㅎㅎ 아직 돌아가는 걸 테스트해보진 않아서 좀 더 고칠 부분이 있을 것 같긴 한데 좋은 것 같아요 😄 저는 개인적으로는 koin 보다 좋은 것 같습니다!

2021-01-26 12:12 UTC, BeokBeok commented on buildSrc/src/main/java/Dependency.kt
> +    private const val VERSION = "2.28-alpha"
> 앗 안드로이드 공식 문서를 보고 따라했는데 거기에는 2.28-alpha라고 적혀있어서 이게 최신 버전으로 알았습니다 ㅠㅠ!! 알려주셔서 감사해요!

혹시 한국어로 된 안드로이드 공식 문서를 보셨나요? 한국어로 된 공식 문서는 업데이트가 느립니다.
영어로 보시는 것을 권장합니다 😄

2021-01-26 12:19 UTC, BeokBeok approved these changes
LGTM 👊 ✌️ 🖐️ 

> implementation을 사용하면 제대로 못 불러와서 에러가 나길래 api를 사용하도록 변경했습니다!

혹시 왜 못불러오는지 아시나요? 🤔

2021-01-26 12:41 UTC, kimdoori commented
> > implementation을 사용하면 제대로 못 불러와서 에러가 나길래 api를 사용하도록 변경했습니다!
> 
> 혹시 왜 못불러오는지 아시나요? 🤔

 트러블 슈팅에는 이 [글](https://stackoverflow.com/a/65741105)을 참고했습니다! 제가 이해한 게 정확하지는 않을 수도 있는데 domain 모듈의 repository에서 data 모듈의 data source를 의존하는데 이는 service에 의존하고, service는 retrofit에 의존하는데, domain 모듈에서 data 모듈의 의존성을 추가할 때 implementation을 사용하면 retrofit은 불러오지 못해서 에러가 나는 것 같습니다!

2021-01-26 12:41 UTC, kimdoori commented on buildSrc/src/main/java/Dependency.kt
> +    private const val VERSION = "2.28-alpha"
> 혹시 한국어로 된 안드로이드 공식 문서를 보셨나요? 한국어로 된 공식 문서는 업데이트가 느립니다.
영어로 보시는 것을 권장합니다 😄

앗... 넵 한국어로 된 문서를 봤습니다 ㅠㅠㅠ 앞으로는 영어 문서로 봐야겠네요ㅠㅠ 알려주셔서 감사합니다!!

2021-01-26 12:42 UTC, kimdoori commented
@BeokBeok  빠른 리뷰 감사합니다!! 머지할게요 😄

(위에 코멘트에 대한 노티를 받지 못하셨을 것 같아서 따로 멘션 드립니다!)

2021-01-26 12:42 UTC, merged

2021-01-26 14:25 UTC, BeokBeok commented
> 트러블 슈팅에는 이 글을 참고했습니다! 제가 이해한 게 정확하지는 않을 수도 있는데 domain 모듈의 repository에서 data 모듈의 data source를 의존하는데 이는 service에 의존하고, service는 retrofit에 의존하는데, domain 모듈에서 data 모듈의 의존성을 추가할 때 implementation을 사용하면 retrofit은 불러오지 못해서 에러가 나는 것 같습니다!

말씀하신 부분이 맞는 것 같네요 👍 

저는 Room 을 사용할 때 이와 유사한 경험을 했었습니다.
Room 에서는 Application Context 가 필요한데, Dagger 특성 상 Application 이 있는 모듈이 Application Context 를 쓰는 모듈을 알아야 Application Context 가 inject 가 되어서 `api` 를 사용해서 의존성을 추가했던 것으로 기억합니다.
이 기억을 바탕으로 도도 포인트앱 클린 아키텍쳐 구조로 적용할 때, 자연스럽게 `api` 를 사용했던 것 같네요 😅 

domain 모듈에서 `api project(":data")` 를 하게 되면, domain 모듈을 implementation 하는 app 모듈에서도 data 모듈이 접근 가능하기 때문에, domain 모듈에서 Retrofit 을 implementation 을 하고 data 모듈의 의존성을 api 에서 implementation 으로 바꾸는 것이 좋을 것 같습니다 😄 

두두님 덕분에 하나의 사례로 이와 비슷한 사례도 동일한 문제일 것이라고 판단했던 부분들을 바로 잡게 되었네요
감사합니다 👍  

(저도 부족한 게 많습니다 😭 )

2021-01-26 15:24 UTC, kimdoori commented
@BeokBeok 우아 친절한 설명 감사합니다!! 말씀대로 Retrofit을 implementation하고, data 모듈도 다시 implementation로 변경하는 게 좋겠네요!! 이건 다음 이슈에서 같이 진행해두겠습니다!! 

항상 감사합니다 😄