GitHub Repository 리스트를 보여주는 화면을 구현합니다.
kimdoori/GitHubApp pull request #18
Opened 2021-01-27 13:14 UTC by kimdoori

# tl;dr

GitHub Repository 리스트를 보여주는 화면을 구현합니다.

5주차 목표: https://github.com/kimdoori/GitHubApp/issues/17 ViewModel을 구현합니다.

# 주요 변경 내용

- GitHub Repository 리스트를 보여주는 presentation layer를 구현합니다.
  - 리스트를 불러오는 동작을 ViewModel에 구현했습니다.
  - 응답을 보여주기 위해 (예쁘지 않은) UI를 추가했습니다.
  - RecyclerView와 databinding을 사용했습니다.
  - description이 nullable이길래 타입을 변경했습니다.
- 실제 돌아가는 걸 테스트하면서 기존 코드의 잘못 되었던 부분들을 고쳤습니다.

## 스크린샷

<img src="https://user-images.githubusercontent.com/22957868/105995688-add68e80-60ec-11eb-866d-a73f93343a75.png" width="300">

# 코드 리뷰

작업별로 커밋해서 커밋이 좀 많습니다 😅  files changed로 봐주세요!
항상 리뷰 봐주셔서 감사합니다 😊 

## 참고 사항

저는 참..... 예쁘게 만드는 것과는 거리가 먼 것 같아요......

2021-01-27 14:00 UTC, BeokBeok commented
> #16 (comment) 이 이슈를 반영하려고 했는데 data 모듈 의존성을 implementation으로 변경하고 다른 의존성들을 명시해줘도 에러가 나길래 디깅해봤는데 cannot access GitHubRepoRemoteDataSource 요런 에러가 발생하는 걸 알게 됐습니다. data 모듈의 다른 의존성을 불러오지 못해서가 아니라 data 모듈의 data source를 접근하지 못해서 발생하는 에러였습니다 😓 그래서 api 를 사용해서 의존성을 추가하도록 그대로 뒀습니다!

저도 제가 잘못 알았나 싶었어서 다시 해봤었는데, 결국 제가 추측한 원인이 맞는 것 같네요 😅 
koin 을 쓰시면 에러가 발생하지 않을 것입니다.
그 이유는 런타임과 컴파일 의존성 주입의 차이점이라고 생각하시면 될 것 같습니다

2021-01-27 14:19 UTC, BeokBeok requested changes
약간의 질문과 의견을 남겼습니다 😄

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/view/MainActivity.kt
> +        viewModel.fetchGitHubRepoList(userName = "kimdoori")
나중에 UI에서 userName을 입력받게 하면 좋을 것 같네요 😄

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +abstract class BaseAdapter<ITEM_TYPE : Any> : RecyclerView.Adapter<BaseViewHolder<ITEM_TYPE>>() {
```suggestion
abstract class BaseAdapter<T> : RecyclerView.Adapter<BaseViewHolder<T>>() {
```

제네릭은 통상적으로 타입이 하나인 경우에는 T 로만 작성하고 어떤 타입인지 생략합니다.
만약에 제네릭이 두 개 이상인 경우에도 알파벳 하나로만 작성하는 경우가 있지만
가독성을 위해 타입을 추가해주면 좋긴 합니다 😄

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +    open fun replaceItems(items: List<ITEM_TYPE>) {
이 함수가 open 인 이유가 있을까요? 🤔

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +        this.items.addAll(items)
run 으로 감싸면 좋을 것 같네요 😄

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/view/GitHubRepoAdapter.kt
> +    )
이 로직을 BaseAdapter 에 위치시키면 어떨까요?
그러면 GithubRepoAdapter 를 만들지 않고, BaseAdapter 를 가지고 적용할 수 있을 것 같습니다 😄

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +open class BaseViewHolder<ITEM_TYPE : Any>(
이 클래스가 open 인 이유가 있나요?

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +    private val bindingVariableId: Int = BR.item
bindingBariableId 는 기본값이 없는 것이 좋을 것 같습니다

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +    LayoutInflater.from(parent.context).inflate(layoutResourceId, parent, false)
```suggestion
    LayoutInflater
        .from(parent.context)
        .inflate(layoutResourceId, parent, false)
```

여기도 함수 체이닝 컨벤션을 적용하면 좋을 것 같네요

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +    open fun bind(item: ITEM_TYPE) {
이 함수가 open 인 이유가 있나요?

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +            )
에러에 대한 로직도 들어가면 좋을 것 같아요

2021-01-27 14:19 UTC, BeokBeok commented on data/src/main/java/com/kimdoori/githubapp/data/di/NetworkModule.kt
> +                .addLast(KotlinJsonAdapterFactory())
KotlinJsonAdapterFactory 도 DI 적용하면 좋을 것 같아요

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +        this.items.addAll(items)
이펙티브 코틀린 서적에서 본 내용같은데요
멤버 변수의 이름과 파라미터의 이름을 다르게 하는 것이 좋습니다
this 를 사용하여 쉐도잉을 피할수 있지만, this 로 구분해줘야한다는 점이 불편합니다
해서, 파라미터 앞에 new 같은 prefix 를 붙여줘서 멤버 변수와 구분하면 어떨까요?

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +            .observeOn(AndroidSchedulers.mainThread())
혹시 subscribeOn 과 observeOn 의 차이점을 아시나요?

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_repoRecyclerView"
xml 은 snake case 가 컨벤션입니다 😄

2021-01-27 14:19 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            android:nestedScrollingEnabled="false"
nestedScrollingEnabled 속성은 어떤 이유로 주신 것인가요?

2021-01-27 14:19 UTC, BeokBeok commented on buildSrc/src/main/java/Dependency.kt
> +    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview:1.1.0"
팁을 드리자면, material 디펜던시를 사용하면 appcompat 과 recyclerview 두개를 대체할 수 있습니다

2021-01-27 14:20 UTC, BeokBeok commented
> 저는 참..... 예쁘게 만드는 것과는 거리가 먼 것 같아요......

대부분의 개발자가 그러지 않나요? 😅

2021-01-28 02:02 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/view/MainActivity.kt
> +        viewModel.fetchGitHubRepoList(userName = "kimdoori")
앗 저 이거 리뷰 보시기 전에  "일단 제 닉네임으로 넣었는데 기능 고도화하면서 닉네임 검색할 수 있게 바꾸려고 합니다 😄" 라고 달아놓으려고 했는데 리뷰로 들어가 버려서 submit이 안됐네요ㅠㅠㅠ 

제안 감사합니다! ㅎㅎ

2021-01-28 11:28 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +            )
에러 처리는 기능 고도화 하면서 다루려고 합니다!! 인디케이터를 띄우려고 합니다 ㅎㅎ 이것도 작성해두는 걸 깜빡했네요 😅

2021-01-28 11:30 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +            .observeOn(AndroidSchedulers.mainThread())
subscribeOn은 작업을 돌리는? 쓰레드를 정할 때 사용하고, observeOn은 작업이 끝나고 실행되는 쓰레드를 정할 때 사용한다고 알고 있습니다!! 쓰레드는 서버 작업이 끝나고 ui를 업데이트할 거라서 AndroidSchedulers.mainThread()를 사용했습니다!

2021-01-28 11:31 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_repoRecyclerView"
앗! 카트의 습관이.... 감사합니다!

2021-01-28 11:32 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +            android:nestedScrollingEnabled="false"
거의 항상 ScrollView 안에 RecyclerView를 두게 돼서 이젠 RecyclerView를 사용할 때 습관이 되어버렸네요... 관성은 참 무서운 것입니다........

2021-01-28 11:32 UTC, kimdoori commented on buildSrc/src/main/java/Dependency.kt
> +    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview:1.1.0"
와우 감사합니다!!

2021-01-28 12:03 UTC, kimdoori commented
> > #16 (comment) 이 이슈를 반영하려고 했는데 data 모듈 의존성을 implementation으로 변경하고 다른 의존성들을 명시해줘도 에러가 나길래 디깅해봤는데 cannot access GitHubRepoRemoteDataSource 요런 에러가 발생하는 걸 알게 됐습니다. data 모듈의 다른 의존성을 불러오지 못해서가 아니라 data 모듈의 data source를 접근하지 못해서 발생하는 에러였습니다 😓 그래서 api 를 사용해서 의존성을 추가하도록 그대로 뒀습니다!
> 
> 저도 제가 잘못 알았나 싶었어서 다시 해봤었는데, 결국 제가 추측한 원인이 맞는 것 같네요 😅
> koin 을 쓰시면 에러가 발생하지 않을 것입니다.
> 그 이유는 런타임과 컴파일 의존성 주입의 차이점이라고 생각하시면 될 것 같습니다

그런 차이가 있군요?! 설명 감사합니다!! 🙇

2021-01-28 12:19 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_repoRecyclerView"
https://github.com/kimdoori/GitHubApp/pull/18/commits/5be489dfeec510e3d56afcdc44dd4e8d2e423baf 반영했습니다!

2021-01-28 12:20 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +            android:nestedScrollingEnabled="false"
https://github.com/kimdoori/GitHubApp/pull/18/commits/99d91a4a41f53ac0093265f7ffa8df2849ee0b46 지웠습니다!

2021-01-28 12:21 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +abstract class BaseAdapter<ITEM_TYPE : Any> : RecyclerView.Adapter<BaseViewHolder<ITEM_TYPE>>() {
https://github.com/kimdoori/GitHubApp/pull/18/commits/9994b94c66e1eb3ca6f67565b4fc00228e8924e7 T로 변경했습니다! 이 커밋에 BaseAdapter, BaseViewHolder 관련 리뷰들이 같이 있습니다!

2021-01-28 12:21 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +    open fun replaceItems(items: List<ITEM_TYPE>) {
없습니다 ㅎㅎ..

2021-01-28 12:21 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +        this.items.addAll(items)
제안 감사합니다!! 둘 다 반영했습니다! ㅎㅎ

2021-01-28 12:22 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/view/GitHubRepoAdapter.kt
> +    )
반영했습니다! BaseAdapter, BaseViewHolder 리팩토링 커밋에 같이 포함했습니다 😄

2021-01-28 12:22 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +open class BaseViewHolder<ITEM_TYPE : Any>(
없습니다 ㅎㅎㅎㅎㅎ...

2021-01-28 12:22 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +    private val bindingVariableId: Int = BR.item
반영했습니다 👍

2021-01-28 12:23 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +    LayoutInflater.from(parent.context).inflate(layoutResourceId, parent, false)
반영했습니다!

2021-01-28 12:23 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseViewHolder.kt
> +    open fun bind(item: ITEM_TYPE) {
없습..니..다...

2021-01-28 12:24 UTC, kimdoori commented on buildSrc/src/main/java/Dependency.kt
> +    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview:1.1.0"
https://github.com/kimdoori/GitHubApp/pull/18/commits/c4cf589580a73dbd28025614b825680725cbb623 반영했습니다! ㅎㅎ

2021-01-28 12:24 UTC, kimdoori commented on data/src/main/java/com/kimdoori/githubapp/data/di/NetworkModule.kt
> +                .addLast(KotlinJsonAdapterFactory())
https://github.com/kimdoori/GitHubApp/pull/18/commits/ae545b330355596a4ff96b76ddc6fffcd7870840 반영했습니다! 😄

2021-01-28 12:25 UTC, kimdoori commented
@BeokBeok 리뷰 감사합니다 😊  전부 반영했습니다!!

2021-01-29 00:52 UTC, BeokBeok reviewed
하나의 코맨트가 있습니다 😄 

그리고 최대한 리뷰단위로 커밋을 하시는 습관을 들이면 좋을 것 같습니다 🙏

2021-01-29 00:52 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +    fun replaceItems(new_items: List<T>) {
코틀린은 camel case 가 컨벤션입니다 😄

2021-01-29 00:53 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +            .observeOn(AndroidSchedulers.mainThread())
생산자와 소비자의 관점에서 말씀해주시면 더 좋을 것 같습니다 👍

2021-01-29 02:31 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +    fun replaceItems(new_items: List<T>) {
아!!!!! 이런......... 이런 실수를.......

2021-01-29 13:13 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +            .observeOn(AndroidSchedulers.mainThread())
관련해서 정확히 모르고 있는 걸 알게 되어 리서치 후 답변 답니다! ㅎㅎ

- 데이터를 생성하고 전달하는 것을 생산자, 생산자가 생성한 데이터를 받아서 처리하는 것을 소비자라고 합니다.
- subscribeOn은 생산에 어떤 쓰레드를 사용할지 지정할 수 있고, observeOn은 소비에 어떤 쓰레드를 사용할지 지정할 수 있습니다.
- subscribeOn만 지정하는 경우 subscribeOn로 지정한 쓰레드 종류로 생산과 소비 둘 다 합니다.

2021-01-29 13:13 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewcommon/BaseAdapter.kt
> +    fun replaceItems(new_items: List<T>) {
https://github.com/kimdoori/GitHubApp/pull/18/commits/fb24e1bd0406d0be77403b29343109b404e4d5da 반영했습니다!

2021-01-29 13:14 UTC, kimdoori commented
> 그리고 최대한 리뷰단위로 커밋을 하시는 습관을 들이면 좋을 것 같습니다 🙏

아!! 묶을 수 있는 건 최대한 묶는 게 더 보시기 편할 거라고 생각했는데 아니었군요 😅  참고하겠습니다!!

2021-01-29 13:15 UTC, kimdoori commented
@BeokBeok 리뷰 감사합니다! 반영했습니다 😊

2021-01-29 13:31 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +            .observeOn(AndroidSchedulers.mainThread())
아주 좋습니다 👍 👍 👍

2021-01-29 13:33 UTC, BeokBeok commented
> 아!! 묶을 수 있는 건 최대한 묶는 게 더 보시기 편할 거라고 생각했는데 아니었군요 😅 참고하겠습니다!!

리뷰 단위로 커밋을 눌러서 일일히 확인하는 것이 더 편합니다
최대한 묶게 되면, 이 커밋이 어떤 리뷰들을 포함하고 있는 지 보기가 어렵습니다 😅

2021-01-29 13:34 UTC, BeokBeok approved these changes
LGTM 👊 ✌️ 🖐️

2021-01-29 13:55 UTC, kimdoori commented
> > 아!! 묶을 수 있는 건 최대한 묶는 게 더 보시기 편할 거라고 생각했는데 아니었군요 😅 참고하겠습니다!!
> 
> 리뷰 단위로 커밋을 눌러서 일일히 확인하는 것이 더 편합니다
> 최대한 묶게 되면, 이 커밋이 어떤 리뷰들을 포함하고 있는 지 보기가 어렵습니다 😅

그렇군요!! 앞으로는 리뷰 별로 커밋하도록 하겠습니다😄

2021-01-29 13:55 UTC, kimdoori commented
확인 감사합니다😆

2021-01-29 13:55 UTC, merged