username을 입력해서 GitHub Repository를 검색할 수 있도록 합니다.
kimdoori/GitHubApp pull request #20
Opened 2021-02-07 14:13 UTC by kimdoori

# tl;dr

#19 

# 주요 변경 내용

- username을 입력해서 repository를 검색할 수 있는 기능을 추가합니다.

<img src="https://user-images.githubusercontent.com/22957868/107149055-f23e1600-6999-11eb-995f-f2a30591e9a0.png" width="300"> <img src="https://user-images.githubusercontent.com/22957868/107149059-f5390680-6999-11eb-82f1-feeec21bb218.png" width="300"> <img src="https://user-images.githubusercontent.com/22957868/107149062-f833f700-6999-11eb-8fb8-80266f23da16.png" width="300">

# 코드 리뷰

이번 주는 시간이 많지 않아서 스콥이 작네요 😓

2021-02-07 14:46 UTC, BeokBeok requested changes
UI 를 구현하느라 수고하셨습니다 😄 
약간의 코맨트가 있습니다 😄 

---

추가로 패키지 관련하여 제안이 있습니다.
1. 패키지명에 underscore 를 빼는 것이 좋습니다.
2. view 와 viewmodel 은 하나의 패키지에 있는 것이 좋습니다.
3. 화면 단위의 패키지명을 정하는 것이 좋습니다.
4. 패키지명은 가급적이면 한 단어로 작성하는 것이 좋습니다.

[Coding Conventions - Naming rules](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules)

2021-02-07 14:46 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/binding_adapter/ViewBindingAdapter.kt
> +    }
```suggestion
    view.isVisible = isVisible
```

ktx 를 사용하시면 한 줄로도 가능합니다 😄

2021-02-07 14:46 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModelImpl.kt
> +class MainViewModelImpl @ViewModelInject constructor(
주로 `impl` 이라는 용어는 인터페이스를 구현할 때 붙입니다.
본 경우에는 상속을 했기 때문에 impl 은 어색해 보이네요

2021-02-07 14:46 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +abstract class MainViewModel : ViewModel() {
abstract class 보다 interface 가 적합해 보입니다

2021-02-07 14:46 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModelImpl.kt
> +    override val loading = MutableLiveData<Boolean>()
외부에서도 해당 라이브데이터에 접근해서 값을 변경할 수 있지 않을까요?

2021-02-07 14:46 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +                app:theme="@style/SearchViewStyle" />
SearchView 도 스크롤이 되어야 하나요?

2021-02-07 14:46 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +                android:layout_width="match_parent"
ConstraintLayout 에는 match_parent 대신 0dp 를 권장합니다

2021-02-07 14:46 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +                android:visibility="gone"
```suggestion
```
없어도 되지 않나요?

2021-02-08 11:20 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModelImpl.kt
> +    override val loading = MutableLiveData<Boolean>()
앗!! 요기는 immutable 해야 하는데 깜빡했군요ㅠ

2021-02-08 11:54 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/binding_adapter/ViewBindingAdapter.kt
> +    }
감사합니다!! https://github.com/kimdoori/GitHubApp/pull/20/commits/f4c19da82221cc256ced2d45e79f596e59e7d0f3 반영했습니다~!

2021-02-08 11:54 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +                android:visibility="gone"
ㅎㅎㅎ 지웠습니다! https://github.com/kimdoori/GitHubApp/pull/20/commits/ced2dcb5798c85ec20206c798e78139c38d582b6

2021-02-08 11:55 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +                android:layout_width="match_parent"
앗 알려주셨던 부분인데 깜빡했네요ㅠㅠ https://github.com/kimdoori/GitHubApp/pull/20/commits/e9d1b37ccb4ffc9894cd1577db4ff5552b236f6a

2021-02-08 11:55 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +                app:theme="@style/SearchViewStyle" />
아니요! 생각해보니 그럴 필요가 없을 것 같아서 ScrollView를 지웠습니다! https://github.com/kimdoori/GitHubApp/pull/20/commits/a34d5e0f745203a3b043f0d72dd8a5bd1ca98515

2021-02-08 11:56 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModelImpl.kt
> +    override val loading = MutableLiveData<Boolean>()
아앗 헷갈려서 잘못 달았네요!
가시성 제한자를 변경했는데 다른 리뷰에서 interface로 변경하면서 deprecated 되었어요ㅠ https://github.com/kimdoori/GitHubApp/pull/20/commits/7ee491624f29cd3c9246bc0be426e87f3ac4a13a

interface는 가시성 제한자를 설정할 수 없던데 좋은 방법이 있을까요?!

2021-02-08 11:57 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModel.kt
> +abstract class MainViewModel : ViewModel() {
ViewModel을 상속 받고 싶어서 abstract class로 했는데 interface로 변경했습니다! https://github.com/kimdoori/GitHubApp/pull/20/commits/d9e50b974de9c7032548ea7827950173078c9c8c

2021-02-08 11:57 UTC, kimdoori commented
> UI 를 구현하느라 수고하셨습니다 😄
> 약간의 코맨트가 있습니다 😄
> 
> 추가로 패키지 관련하여 제안이 있습니다.
> 
> 1. 패키지명에 underscore 를 빼는 것이 좋습니다.
> 2. view 와 viewmodel 은 하나의 패키지에 있는 것이 좋습니다.
> 3. 화면 단위의 패키지명을 정하는 것이 좋습니다.
> 4. 패키지명은 가급적이면 한 단어로 작성하는 것이 좋습니다.
> 
> ref. [Coding Conventions - Naming rules](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules)

감사합니다!!! 전체적으로 리팩토링했습니다! https://github.com/kimdoori/GitHubApp/pull/20/commits/80f0dc7f3bf8f3196fa3758d3ac9f43bbe48283c

2021-02-08 11:58 UTC, kimdoori commented on app/src/main/res/layout/activity_main.xml
> +                app:theme="@style/SearchViewStyle" />
잘못 들어간 빈 줄도 지웠습니다! https://github.com/kimdoori/GitHubApp/pull/20/commits/edfe9ee4300f9a6a8f825fa81ab1427582916bda

2021-02-08 11:59 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModelImpl.kt
> +class MainViewModelImpl @ViewModelInject constructor(
그렇군요?! 감사합니다!! interface로 변경해서 이 부분은 납뒀습니다!

2021-02-08 11:59 UTC, kimdoori commented
@BeokBeok 리뷰 감사합니다!!! 반영했습니다 😊

2021-02-08 12:13 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModelImpl.kt
> +    override val loading = MutableLiveData<Boolean>()
제가 리뷰를 잘 못 달았네요 😭 
MainViewModel 을 abstract class 로 하시고, githubRepoList 와 loading 의 접근자에 `protected` 를 붙여주시면 외부에서 접근이 불가합니다

상속받는 곳에서 override 를 하기 때문에, 이름도 impl 이 적합하긴 하겠네요 😄 
죄송합니다 🙏

2021-02-08 12:14 UTC, BeokBeok reviewed
리뷰를 잘 못 단 것이 있어서 코맨트를 추가하였습니다 😅

2021-02-08 12:40 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/viewmodel/MainViewModelImpl.kt
> +    override val loading = MutableLiveData<Boolean>()
https://github.com/kimdoori/GitHubApp/pull/20/commits/176b9a559188e292afd42d57999bd3a195dd6ba5 다시 돌려놨습니다! ㅎㅎ 감사해요!! 앞으로는 무조건적으로 반영하기 보다는 의문을 좀 품어봐야겠네요 ㅎㅎ

2021-02-08 12:41 UTC, kimdoori commented
@BeokBeok 반영했습니다!! 시간 내주셔서 감사해요 😆

2021-02-08 12:46 UTC, BeokBeok approved these changes
LGTM 👊 ✌️ 🖐️ 

저도 틀릴수도 있고 부족한점이 많습니다 😅 
레아님에게도 말씀드렸던 부분이긴 한데요
제가 강압적으로 무논리로 밀어부치는(?) 일은 없겠지만, 만약 제가 그렇다 하더라도
의문을 갖고 이해가 되지 않으시면 이해될 때까지 계속 물어보셨으면 좋겠습니다 🙏 😄 
혹여나 제가 기분이 상할까봐 걱정하지 않으셔도 됩니다~ ✌️

2021-02-08 13:20 UTC, kimdoori commented
> LGTM 👊 ✌️ 🖐️
> 
> 저도 틀릴수도 있고 부족한점이 많습니다 😅
> 레아님에게도 말씀드렸던 부분이긴 한데요
> 제가 강압적으로 무논리로 밀어부치는(?) 일은 없겠지만, 만약 제가 그렇다 하더라도
> 의문을 갖고 이해가 되지 않으시면 이해될 때까지 계속 물어보셨으면 좋겠습니다 🙏 😄
> 혹여나 제가 기분이 상할까봐 걱정하지 않으셔도 됩니다~ ✌️

감사합니다!!! 항상 저희를 위해 배려해주시고 노력해주셔서 감사해요 😊  
덕분에 많이 성장하고 있습니다 ㅎㅎㅎ!!

2021-02-08 13:20 UTC, merged