GitHub Repository에 해당하는 Pull Request 리스트를 조회할 수 있는 상세 화면을 구현합니다.
kimdoori/GitHubApp pull request #22
Opened 2021-02-12 11:12 UTC by kimdoori

# tl;dr

#21

# 주요 변경 내용

GitHub Repository에 해당하는 Pull Request 리스트를 조회할 수 있는 상세 화면을 구현합니다.

<img src="https://user-images.githubusercontent.com/22957868/107760902-dbb70680-6d6d-11eb-8c9e-f4a9b3f25073.png" width="300"> <img src="https://user-images.githubusercontent.com/22957868/107760910-dd80ca00-6d6d-11eb-9187-02977a17b345.png" width="300">

# 코드 리뷰

https://github.com/kimdoori/GitHubApp/commit/e3e3a608dd347e6aed68b353c08e0a9ace2a63aa 관련해서 고민이 있습니다!
ViewModel - ViewModelImpl 구조를 변경할까요? 🤔 
저번에 아티클 정리했던 내용을 반영한 건데 view에서 binding 하려면 public 해야 하는데, 외부에서 수정할 수 없게 하고 싶고... 좋은 방법이 있을까요?!

## 참고 사항

UI와 UX를 신경쓰지 않고 클린 아키텍처로 pull request 리스트를 조회할 수 있는 기능을 구현하는 걸 목표로 했습니다.

2021-02-12 11:46 UTC, BeokBeok commented
@kimdoori 
> e3e3a60 관련해서 고민이 있습니다!
ViewModel - ViewModelImpl 구조를 변경할까요? 🤔
저번에 아티클 정리했던 내용을 반영한 건데 view에서 binding 하려면 public 해야 하는데, 외부에서 수정할 수 없게 하고 싶고... 좋은 방법이 있을까요?!

A. 이펙티브 자바에도 수록된 내용이지만, [Item 36. 상속보다는 컴포지션을 선호하라](https://www.notion.so/beokbeok/Item-36-fad04cbd14fc43d99db3225c6cadc240) 이 글을 보시면 도움이 될 것 같아요 😄

2021-02-13 12:45 UTC, BeokBeok requested changes
연휴인데도 공부하시느라 고생 많으셨습니다 😄 

약간의 코맨트가 있습니다

2021-02-13 12:45 UTC, BeokBeok commented on domain/src/main/java/com/kimdoori/githubapp/domain/usecase/PullRequestUseCaseImpl.kt
> +            }
메서드 참조 👍

2021-02-13 12:45 UTC, BeokBeok commented on domain/src/main/java/com/kimdoori/githubapp/domain/model/PullRequestModel.kt
> +                ?.map { UserModel.mapFromEntity(it) },
```suggestion
                ?.map(UserModel::mapFromEntity),
```

2021-02-13 12:45 UTC, BeokBeok commented on domain/src/main/java/com/kimdoori/githubapp/domain/model/PullRequestModel.kt
> +    val requestedReviewers: List<UserModel?>? = null,
기본값을 null 이 아닌 emptyList 는 어떨까요?

2021-02-13 12:45 UTC, BeokBeok commented on domain/src/main/java/com/kimdoori/githubapp/domain/model/PullRequestModel.kt
> +            assignee = pullRequestResponse.assignee?.let { UserModel.mapFromEntity(it) },
```suggestion
            assignee = pullRequestResponse.assignee?.let(UserModel::mapFromEntity),
```

2021-02-13 12:45 UTC, BeokBeok commented on app/src/main/res/layout/activity_repo_detail.xml
> +        android:orientation="vertical"
```suggestion
```
불필요한 속성으로 보입니다 😄

2021-02-13 12:45 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/main/MainViewModel.kt
> +    abstract val loading: LiveData<Boolean>
protected 접근자가 없으면, 뷰에서 직접 값을 변경할 수 있지 않나요? 🤔

2021-02-13 12:45 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/detail/RepoDetailViewModelImpl.kt
> +                    loading.value = false
에러가 발생했을 때 토스트 혹은 다이얼로그같은 것을 띄워주면 좋을 것 같습니다 😄

2021-02-13 12:45 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/detail/RepoDetailActivity.kt
> +        if (userName == null || repoName == null) return
```suggestion
        val userName = intent.getStringExtra(EXTRA_USER_NAME) ?: return
        val repoName = intent.getStringExtra(EXTRA_REPO_NAME) ?: return
```
이렇게도 사용할 수 있을 것 같습니다 😄

2021-02-14 04:39 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/detail/RepoDetailViewModelImpl.kt
> +                    loading.value = false
의견 감사합니다!! 요건 고도화하면서 반영해볼게요!!

2021-02-14 04:40 UTC, kimdoori commented on domain/src/main/java/com/kimdoori/githubapp/domain/model/PullRequestModel.kt
> +            assignee = pullRequestResponse.assignee?.let { UserModel.mapFromEntity(it) },
감사합니다!! 자꾸 깜빡하네요.... 메모메모..
https://github.com/kimdoori/GitHubApp/pull/22/commits/3768a8ad82b11f5a0579330bdfd6edd93e877adb

2021-02-14 04:40 UTC, kimdoori commented on domain/src/main/java/com/kimdoori/githubapp/domain/model/PullRequestModel.kt
> +                ?.map { UserModel.mapFromEntity(it) },
https://github.com/kimdoori/GitHubApp/pull/22/commits/3768a8ad82b11f5a0579330bdfd6edd93e877adb 반영했습니다!

2021-02-14 04:40 UTC, kimdoori commented on app/src/main/res/layout/activity_repo_detail.xml
> +        android:orientation="vertical"
https://github.com/kimdoori/GitHubApp/pull/22/commits/8b1f7e50c1e6e302e32ad28a52438a7d5e7af8cf 감사합니다!

2021-02-14 04:41 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/detail/RepoDetailActivity.kt
> +        if (userName == null || repoName == null) return
제안 감사합니다! https://github.com/kimdoori/GitHubApp/pull/22/commits/8efbddf4593d082ae2dbc46a356a3b1290728b8d

2021-02-14 05:57 UTC, kimdoori commented on domain/src/main/java/com/kimdoori/githubapp/domain/model/PullRequestModel.kt
> +    val requestedReviewers: List<UserModel?>? = null,
좋습니다! 반영했습니다!! https://github.com/kimdoori/GitHubApp/pull/22/commits/87407c860de0eb6c6dbcfc234c8f8f1ca20fcb2d

2021-02-14 05:59 UTC, kimdoori commented on app/src/main/java/com/kimdoori/githubapp/main/MainViewModel.kt
> +    abstract val loading: LiveData<Boolean>
https://github.com/kimdoori/GitHubApp/pull/22#issuecomment-778148147 요거 참고해서 상속이 아니라 composition으로 변경했습니다!! 반영하면서 외부에서 수정할 수 없도록 변경되었습니다! 레퍼 감사합니다 🙇 

https://github.com/kimdoori/GitHubApp/pull/22/commits/2de2989aa21c6d8082372fd6f5cb0e6eb57dc5e1

2021-02-14 06:02 UTC, kimdoori commented
@BeokBeok 리뷰 감사합니다 😊  반영했습니다!

2021-02-14 07:06 UTC, BeokBeok approved these changes
LGTM 👊 ✌️ 🖐️ 

상속의 단점을 몸소 겪어보시고 컴포지션으로 바꾸니 어떠셨나요? 😄 
이 주제에 대해서 주미때 언급해주시면 좋을 것 같습니다 👍

2021-02-14 09:40 UTC, kimdoori commented
> LGTM 👊 ✌️ 🖐️
> 
> 상속의 단점을 몸소 겪어보시고 컴포지션으로 바꾸니 어떠셨나요? 😄
> 이 주제에 대해서 주미때 언급해주시면 좋을 것 같습니다 👍

처음 겪어봤는데 바꾸는 과정에서 리서치도 많이 하면서 유익한 시간을 보냈습니다!! ㅎㅎ 주미때 언급할게요~! 감사합니다 🙏

2021-02-14 09:41 UTC, merged