Pull Request 상세 화면을 구현합니다.
kimdoori/GitHubApp pull request #24
Opened 2021-02-21 04:12 UTC by kimdoori

# tl;dr

#23

# 주요 변경 내용

- GitHub Repository 상세 화면의 Pull Request 카드를 누르면 PR 웹뷰로 이동하도록 구현합니다.

<img src="https://user-images.githubusercontent.com/22957868/108615286-0546f080-7446-11eb-8f93-bb79e5100338.png" width="300"> <img src="https://user-images.githubusercontent.com/22957868/108615289-0841e100-7446-11eb-85d4-46f6f8e8ed60.png" width="300">

# 코드 리뷰

네이밍 관련 고민이 있습니다.

pull request를 표현하기 위해 카멜 케이스로 쓸 때는 pullRequest로, 스네이크 케이스로 쓸 때는 pullrequest로 작성했는데 스네이크 케이스로 쓸 때 pull_request로 작성하는 게 더 좋을까요?!

## 참고 사항

작업 내용이 생각보다 적네요 😅 
월요일에 시간이 있다면 다른 이슈도 더 진행해보려고 합니다! (검색 결과 없는 경우 처리, 카드 리플 효과 등등)

2021-02-21 12:28 UTC, BeokBeok requested changes
깔끔한 구현이 좋았습니다.
약간의 코맨트가 있습니다 😄

2021-02-21 12:28 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/pullrequest/PullRequestActivity.kt
> +        }
```suggestion
        binding = DataBindingUtil
            .setContentView<ActivityPullrequestBinding>(this, R.layout.activity_pullrequest)
            .apply {
                lifecycleOwner = this@PullRequestActivity
            }
```
함수 체이닝 컨벤션을 지키면 좋을 것 같아요 😄

2021-02-21 12:28 UTC, BeokBeok commented on app/src/main/java/com/kimdoori/githubapp/pullrequest/PullRequestActivity.kt
> +        }
```suggestion
        intent
            .getStringExtra(EXTRA_PULL_REQUEST_URL)
            ?.let {
                binding.pullRequestWebview.loadUrl(it)
            }
```

2021-02-21 12:28 UTC, BeokBeok commented on app/src/main/res/layout/item_pullrequest.xml
> +        android:id="@+id/item_pullrequest_root_layout"
```suggestion
        android:id="@+id/item_pull_request_root_layout"
```
요렇게 쓰는 것이 좋을 것 같습니다 😄

2021-02-21 12:30 UTC, BeokBeok commented
> pull request를 표현하기 위해 카멜 케이스로 쓸 때는 pullRequest로, 스네이크 케이스로 쓸 때는 pullrequest로 작성했는데 스네이크 케이스로 쓸 때 pull_request로 작성하는 게 더 좋을까요?!

`pull_request` 로 작성하는 것이 좋을 것 같습니다
카멜 케이스에는 R 을 대문자로 사용함으로써 구별하였기 때문에, 스네이크 케이스에는 언더바를 사용해서 r 앞에 와야 문맥상 동일할 것으로 보이네요 😄

2021-02-21 14:44 UTC, kimdoori commented
@BeokBeok 리뷰 감사합니다!! 반영했습니다!

2021-02-21 14:45 UTC, BeokBeok commented on app/src/main/res/layout/item_pullrequest.xml
> +        android:id="@+id/item_pullrequest_root_layout"
@kimdoori 요거 하나만 반영해주세요 😄

2021-02-21 14:45 UTC, BeokBeok approved these changes
LGTM 👊 ✌️ 🖐️

2021-02-22 03:06 UTC, kimdoori commented on app/src/main/res/layout/item_pullrequest.xml
> +        android:id="@+id/item_pullrequest_root_layout"
ㅠㅠ 왜 빠트렸지.. 정신이 없었나 보네요ㅠㅠㅠ 제대로 반영했습니다!!

2021-02-22 03:07 UTC, kimdoori commented on app/src/main/res/layout/item_pullrequest.xml
> +        android:id="@+id/item_pullrequest_root_layout"
https://github.com/kimdoori/GitHubApp/pull/24/commits/d9654b7f003913d900c24b1e8fff4b75281c1009 반영했습니다!

2021-02-22 03:07 UTC, kimdoori commented
@BeokBeok 항상 리뷰 봐주셔서 감사합니다! ㅎㅎㅎ 반영했습니다~!

2021-02-22 04:15 UTC, BeokBeok commented
@kimdoori 확인했습니다 👍

2021-02-22 04:59 UTC, merged